# Generated by Django 5.0.4 on 2024-04-22 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('DepartmentID', models.AutoField(primary_key=True, serialize=False)),
                ('DepartmentName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('EmployeeID', models.AutoField(primary_key=True, serialize=False)),
                ('Department', models.CharField(max_length=500)),
                ('DateOFJoining', models.DateField()),
                ('EmployeeName', models.CharField(max_length=500)),
                ('PhotoFileName', models.CharField(max_length=500)),
            ],
        ),
    ]
